name: Deployments
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  build:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            docker stop bollinger-band-screener
            docker rm bollinger-band-screener
            docker pull atilaahmet/bollinger-band-screener:${{ inputs.tag }}
            docker run -d --name bollinger-band-screener -p 5001:5001 atilaahmet/bollinger-band-screener:${{ inputs.tag }}

